version: '3'

services:
  app:
    image: node:18
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - "3000:3000"  # フロントエンド
      - "8787:8787"  # Cloudflare Workers
    environment:
      - NODE_ENV=development

  # モックデータベース
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: randomjourney
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 