name = "seishun18-random-journey-api"
main = "src/index.ts"
compatibility_date = "2023-08-01"

[vars]
ENVIRONMENT = "production"

# D1データベースの設定
[[d1_databases]]
binding = "DB"
database_name = "random_journey_db"
database_id = "placeholder-db-id"

# 開発環境の設定
[env.development]
vars = { ENVIRONMENT = "development" }

# 本番環境の設定
[env.production]
routes = [
  { pattern = "api.randomjourney.example.com", custom_domain = true }
]

# ローカル開発用の設定
[dev]
port = 8787
local_protocol = "http" 