name = "seishun18-random-journey-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
FRONTEND_ORIGIN = "http://localhost:5173"
EKISPERT_API_KEY = ""

[[kv_namespaces]]
binding = "STATION_CACHE"
id = "90a8015b8db24ff8bc6cde285504858e"
